services:
  backend:
    profiles:
      - local-mount
    image: ghcr.io/arboreumdev/tusker-pilot-backend:docker
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      uvicorn main:app --app-dir /app/ --reload --port 8000 --host 0.0.0.0
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  test-db:
    profiles:
      - testing
    image: postgres:12
    env_file:
      - .env
    ports:
      # - "5432:5432"
      - "${POSTGRES_TEST_PORT-5432}:5432"
  db:
    profiles:
      - local-dev
    image: postgres:12
    env_file:
      - .env
    ports:
      # - "5444:5432"
      - "${POSTGRES_PORT}:5432"