"""Initial state

Revision ID: 8bba308b66fd
Revises: 
Create Date: 2021-07-08 14:57:56.377987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bba308b66fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('creditline_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.add_column('invoice', sa.Column('supplier_id', sa.String(length=50), nullable=False))
    op.add_column('invoice', sa.Column('purchaser_id', sa.String(length=50), nullable=False))
    op.add_column('invoice', sa.Column('financed_on', sa.DateTime(), nullable=True))
    op.add_column('invoice', sa.Column('apr', sa.Float(), nullable=True))
    op.add_column('invoice', sa.Column('tenor_in_days', sa.Integer(), nullable=True))
    op.drop_column('invoice', 'receiver_id')
    op.drop_column('invoice', 'customer_id')
    op.drop_column('user', 'customer_id')
    op.add_column('whitelist', sa.Column('supplier_id', sa.String(length=50), nullable=False))
    op.add_column('whitelist', sa.Column('purchaser_id', sa.String(length=50), nullable=False))
    op.add_column('whitelist', sa.Column('location_id', sa.String(length=50), nullable=False))
    op.add_column('whitelist', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('whitelist', sa.Column('phone', sa.String(length=50), nullable=False))
    op.add_column('whitelist', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('whitelist', sa.Column('creditline_size', sa.Integer(), nullable=False))
    op.add_column('whitelist', sa.Column('apr', sa.Float(), nullable=True))
    op.add_column('whitelist', sa.Column('tenor_in_days', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_whitelist_location_id'), 'whitelist', ['location_id'], unique=False)
    op.drop_column('whitelist', 'receiver_id')
    op.drop_column('whitelist', 'receiver_name')
    op.drop_column('whitelist', 'borrower_id')
    op.drop_column('whitelist', 'credit_line_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist', sa.Column('credit_line_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('whitelist', sa.Column('borrower_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('whitelist', sa.Column('receiver_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('whitelist', sa.Column('receiver_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_whitelist_location_id'), table_name='whitelist')
    op.drop_column('whitelist', 'tenor_in_days')
    op.drop_column('whitelist', 'apr')
    op.drop_column('whitelist', 'creditline_size')
    op.drop_column('whitelist', 'city')
    op.drop_column('whitelist', 'phone')
    op.drop_column('whitelist', 'name')
    op.drop_column('whitelist', 'location_id')
    op.drop_column('whitelist', 'purchaser_id')
    op.drop_column('whitelist', 'supplier_id')
    op.add_column('user', sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('invoice', sa.Column('receiver_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('invoice', 'tenor_in_days')
    op.drop_column('invoice', 'apr')
    op.drop_column('invoice', 'financed_on')
    op.drop_column('invoice', 'purchaser_id')
    op.drop_column('invoice', 'supplier_id')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
