"""verified by tusker bool on invoice-table

Revision ID: af4590cd1b0f
Revises: 17b1ca8291be
Create Date: 2021-09-02 14:17:08.552175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4590cd1b0f'
down_revision = '17b1ca8291be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'verified')
    # ### end Alembic commands ###
