"""add purchaser table

Revision ID: d5f2dba9e57c
Revises: af4590cd1b0f
Create Date: 2022-01-06 18:00:16.512152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f2dba9e57c'
down_revision = 'af4590cd1b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchasers',
    sa.Column('purchaser_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('credit_limit', sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchasers')
    # ### end Alembic commands ###
