from utils.constant import RECEIVER_ID1, receiver1, receiver2


RAW_ORDER = {
    "id": "971b4ce5-e8cf-4ab1-b85e-cc9e640b700b",
    "ept": 1443699853000,
    "eta": 1443714253000,
    "status": 21,
    "auto_pickup": False,
    "preferences": {
        "shipper_package_routing_pref": {
        "walk_in": False
        },
        "receiver_package_routing_pref": {
        "walk_in": False
        }
    },
    "attributes": {},
    "not_delivered_near_by": True,
    "crt": 1443699918000,
    "upd": 1597740245000,
    "rd_only": True,
    "crt_from": "WEB",
    "flg": {
        "status": -1,
        "duplicate": False
    },
    "w_flg": 0,
    "consgt": {
        "shipperPaying": True,
        "cat": 4,
        "desc": "1 Box",
        "wt_dcl": [
        2.0
        ],
        "wt_act": [],
        "it_sm": 1,
        "it_lg": 0,
        "val_dcl": 0.0,
        "s_pay": True,
        "ctgry_tgs": [],
        "it_act": 1
    },
    "prc": {
        "payer": {
        "auser": True,
        "o_id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "o_ty": 2,
        "name": "Saturn Entreprises",
        "mob": "+91-9886318900"
        },
        "params": {
        "spkg": 0,
        "lpkg": 0,
        "sur": 0.0,
        "tsur": False,
        "sPay": False,
        "walkInSource": False,
        "walkInDest": False,
        "taxRateOverridden": False,
        "minTaxableAmount": 0.0,
        "sameDepotDeliveryDiscount": 0.0,
        "sameDepotDelivery": False,
        "pricingFactor": 1.0,
        "isPFAutoGenerated": False,
        "isDiscAutoGenerated": False,
        "billingType": 0,
        "dapp": False
        },
        "model": "BOX_BASED",
        "cash_collected": False,
        "net_price": 0.0,
        "sur": 0.0,
        "pr_init": 15.0,
        "disc": 0.0,
        "d_md": 0,
        "pr_act": 15000.0,
        "pr_fx": False,
        "pr_ftr_md": 0,
        "pr_ty": 0,
        "pr_ig": True
    },
    "ref_no": "2015101-001",
    "cust": {
        "id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "status": 0,
        "crt": 1443699918000,
        "upd": 1599031146000,
        "crt_from": "WEB",
        "flg": {
        "status": -1,
        "duplicate": False
        },
        "w_flg": 2,
        "rmk": "Shop closes at 7:00 Pm",
        "cntct": {
        "name": "Saturn Entreprises",
        "f_name": "Saturn Entreprises",
        "p_mob": "+91-9886318900",
        "p_alt": "+91-8362370272"
        },
        "sex": 2,
        "loc": {
        "id": "4d267c22-4c15-4fa5-b2bb-547dba2ee1fb",
        "status": 0,
        "type": 2,
        "addressLine1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
        "crt": 1443699918000,
        "upd": 1599031145000,
        "rd_only": True,
        "crt_from": "WEB",
        "flg": {
            "status": -1,
            "duplicate": False
        },
        "w_flg": 0,
        "pub": False,
        "cntct": {
            "name": "Saturn Entreprises",
            "f_name": "Saturn Entreprises",
            "p_mob": "+91-9886318900",
            "p_alt": "+91-8362370272"
        },
        "addr": {
            "city": "Hubballi",
            "state": "Karnataka",
            "a_l1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
            "plc_id": "da2d60a2-86fc-45ab-8260-e95791569ef2",
            "loc": "vidya nagar",
            "pin": "580021",
            "s_dist": "hubballi",
            "dst": "dharwad",
            "cntry": "IN"
        },
        "geo": {
            "lat": 15.3642251,
            "long": 75.1295622,
            "accr": 20.0,
            "src": "CALC_AUTO"
        },
        "requires_docs_for_pickup": False
        },
        "pref": {
        "lang": "en_US"
        },
        "x_p": 0
    },
    "shppr": {
        "id": "4d267c22-4c15-4fa5-b2bb-547dba2ee1fb",
        "status": 0,
        "type": 2,
        "addressLine1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
        "crt": 1443699918000,
        "upd": 1599031145000,
        "rd_only": True,
        "crt_from": "WEB",
        "flg": {
        "status": -1,
        "duplicate": False
        },
        "w_flg": 0,
        "pub": False,
        "cntct": {
        "name": "Saturn Entreprises",
        "f_name": "Saturn Entreprises",
        "p_mob": "+91-9886318900",
        "p_alt": "+91-8362370272"
        },
        "addr": {
        "city": "Hubballi",
        "state": "Karnataka",
        "a_l1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
        "plc_id": "da2d60a2-86fc-45ab-8260-e95791569ef2",
        "loc": "vidya nagar",
        "pin": "580021",
        "s_dist": "hubballi",
        "dst": "dharwad",
        "cntry": "IN"
        },
        "geo": {
        "lat": 15.3642251,
        "long": 75.1295622,
        "accr": 20.0,
        "src": "CALC_AUTO"
        },
        "requires_docs_for_pickup": False
    },
    "shipper_contact": {
        "auser": True,
        "o_id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "o_ty": 2,
        "name": "Saturn Entreprises",
        "mob": "+91-9886318900"
    },
    "shipper_payee": {
        "auser": True,
        "o_id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "o_ty": 2,
        "name": "Saturn Entreprises",
        "mob": "+91-9886318900"
    },
    "s_dpt": {
        "id": "cc98965e-0422-40d6-992f-89892d595fdb",
        "dummy": False,
        "crt_from": "WEB",
        "def": False
    },
    "rcvr": {
        "id": RECEIVER_ID1,
        "status": 0,
        "type": 2,
        "addressLine1": "opp old bus stand subhas road ",
        "crt": 1594197216000,
        "upd": 1594284393000,
        "rd_only": True,
        "crt_from": "WEB",
        "flg": {
        "status": -1,
        "duplicate": False
        },
        "w_flg": 0,
        "pub": False,
        "cntct": {
        "name": receiver1.name,
        "f_name": "porwal ambe medicals",
        "p_mob": "+91-9986238611"
        },
        "addr": {
        "city": "Dharwad",
        "state": "Karnataka",
        "a_l1": "opp old bus stand subhas road ",
        "plc_id": "18443f1f-9f5e-4e8c-8f99-9dc9bc43ea46",
        "loc": "\"dharwad r s\"",
        "pin": "580007",
        "s_dist": "dharwad",
        "dst": "dharwad",
        "cntry": "IN",
        "lmrk": ""
        },
        "geo": {
        "lat": 15.459898275,
        "long": 75.01109025,
        "accr": 26.126,
        "src": "CALC_AUTO"
        },
        "requires_docs_for_pickup": False
    },
    "receiver_contact": {
        "auser": True,
        "o_id": "0d31eb5f-5caf-491e-961c-bb399e655027",
        "o_ty": 2,
        "name": "Ambe Medical",
        "mob": "+91-8362221260"
    },
    "d_dpt": {
        "id": "1715630f-80e9-4732-8cc1-c3e92fbbf571",
        "dummy": False,
        "crt_from": "WEB",
        "def": False
    },
    "sec": [],
    "ept_w": {
        "start": 1443699853000,
        "end": 1443699853000,
        "anon": False
    },
    "e_eta": 1443714253000,
    "eta_ed": False,
    "c_per": 100,
    "s_updt": 1443761800000,
    "o_dt": 1443699918000,
    "lgl": {
        "toc_acpt": False,
        "invc_issd": False,
        "s_ack": "ackSHIP_IMG_cfdddccd-43b2-43ca-82bf-5ad8cf0dfeca_20151001_171703.jpg"
    },
    "p_mrt": "3f90cfa6-be56-420a-a96f-fb312f0fba37",
    "cust_shpr": False,
    "cust_rcvr": False,
    "u_shpr": False,
    "u_rcvr": False,
    "pck": False,
    "invc_tok": "9sIjQAjKbIhsPogEMe29nQ~~",
    "crt_s": "WEB",
    "trk_ids": [],
    "assoc": False,
    "nearby_delivery": False,
    "rcvr_walk": False,
    "shppr_walk": False
}

NEW_RAW_ORDER = {
    "id": "871b4ce5-e8cf-4ab1-b85e-cc9e640b700b",
    "ept": 1443699853000,
    "eta": 1443714253000,
    "status": 3,
    "auto_pickup": False,
    "preferences": {
        "shipper_package_routing_pref": {
        "walk_in": False
        },
        "receiver_package_routing_pref": {
        "walk_in": False
        }
    },
    "attributes": {},
    "not_delivered_near_by": True,
    "crt": 1443699918000,
    "upd": 1597740245000,
    "rd_only": True,
    "crt_from": "WEB",
    "flg": {
        "status": -1,
        "duplicate": False
    },
    "w_flg": 0,
    "consgt": {
        "shipperPaying": True,
        "cat": 4,
        "desc": "1 Box",
        "wt_dcl": [
        2.0
        ],
        "wt_act": [],
        "it_sm": 1,
        "it_lg": 0,
        "val_dcl": 0.0,
        "s_pay": True,
        "ctgry_tgs": [],
        "it_act": 1
    },
    "prc": {
        "payer": {
        "auser": True,
        "o_id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "o_ty": 2,
        "name": "Saturn Entreprises",
        "mob": "+91-9886318900"
        },
        "params": {
        "spkg": 0,
        "lpkg": 0,
        "sur": 0.0,
        "tsur": False,
        "sPay": False,
        "walkInSource": False,
        "walkInDest": False,
        "taxRateOverridden": False,
        "minTaxableAmount": 0.0,
        "sameDepotDeliveryDiscount": 0.0,
        "sameDepotDelivery": False,
        "pricingFactor": 1.0,
        "isPFAutoGenerated": False,
        "isDiscAutoGenerated": False,
        "billingType": 0,
        "dapp": False
        },
        "model": "BOX_BASED",
        "cash_collected": False,
        "net_price": 0.0,
        "sur": 0.0,
        "pr_init": 15.0,
        "disc": 0.0,
        "d_md": 0,
        "pr_act": 20000.0,
        "pr_fx": False,
        "pr_ftr_md": 0,
        "pr_ty": 0,
        "pr_ig": True
    },
    "ref_no": "2016101-005",
    "cust": {
        "id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "status": 0,
        "crt": 1443699918000,
        "upd": 1599031146000,
        "crt_from": "WEB",
        "flg": {
        "status": -1,
        "duplicate": False
        },
        "w_flg": 2,
        "rmk": "Shop closes at 7:00 Pm",
        "cntct": {
        "name": "Saturn Entreprises",
        "f_name": "Saturn Entreprises",
        "p_mob": "+91-9886318900",
        "p_alt": "+91-8362370272"
        },
        "sex": 2,
        "loc": {
        "id": "4d267c22-4c15-4fa5-b2bb-547dba2ee1fb",
        "status": 0,
        "type": 2,
        "addressLine1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
        "crt": 1443699918000,
        "upd": 1599031145000,
        "rd_only": True,
        "crt_from": "WEB",
        "flg": {
            "status": -1,
            "duplicate": False
        },
        "w_flg": 0,
        "pub": False,
        "cntct": {
            "name": "Saturn Entreprises",
            "f_name": "Saturn Entreprises",
            "p_mob": "+91-9886318900",
            "p_alt": "+91-8362370272"
        },
        "addr": {
            "city": "Hubballi",
            "state": "Karnataka",
            "a_l1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
            "plc_id": "da2d60a2-86fc-45ab-8260-e95791569ef2",
            "loc": "vidya nagar",
            "pin": "580021",
            "s_dist": "hubballi",
            "dst": "dharwad",
            "cntry": "IN"
        },
        "geo": {
            "lat": 15.3642251,
            "long": 75.1295622,
            "accr": 20.0,
            "src": "CALC_AUTO"
        },
        "requires_docs_for_pickup": False
        },
        "pref": {
        "lang": "en_US"
        },
        "x_p": 0
    },
    "shppr": {
        "id": "4d267c22-4c15-4fa5-b2bb-547dba2ee1fb",
        "status": 0,
        "type": 2,
        "addressLine1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
        "crt": 1443699918000,
        "upd": 1599031145000,
        "rd_only": True,
        "crt_from": "WEB",
        "flg": {
        "status": -1,
        "duplicate": False
        },
        "w_flg": 0,
        "pub": False,
        "cntct": {
        "name": "Saturn Entreprises",
        "f_name": "Saturn Entreprises",
        "p_mob": "+91-9886318900",
        "p_alt": "+91-8362370272"
        },
        "addr": {
        "city": "Hubballi",
        "state": "Karnataka",
        "a_l1": "Goudar Bulding, Old income tax office, near seven beans. Alt No: 9449745079",
        "plc_id": "da2d60a2-86fc-45ab-8260-e95791569ef2",
        "loc": "vidya nagar",
        "pin": "580021",
        "s_dist": "hubballi",
        "dst": "dharwad",
        "cntry": "IN"
        },
        "geo": {
        "lat": 15.3642251,
        "long": 75.1295622,
        "accr": 20.0,
        "src": "CALC_AUTO"
        },
        "requires_docs_for_pickup": False
    },
    "shipper_contact": {
        "auser": True,
        "o_id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "o_ty": 2,
        "name": "Saturn Entreprises",
        "mob": "+91-9886318900"
    },
    "shipper_payee": {
        "auser": True,
        "o_id": "cd453e55-8de8-47ae-bd58-dc8ea9b679da",
        "o_ty": 2,
        "name": "Saturn Entreprises",
        "mob": "+91-9886318900"
    },
    "s_dpt": {
        "id": "cc98965e-0422-40d6-992f-89892d595fdb",
        "dummy": False,
        "crt_from": "WEB",
        "def": False
    },
    "rcvr": {
        "id": RECEIVER_ID1,
        "status": 0,
        "type": 2,
        "addressLine1": "opp old bus stand subhas road ",
        "crt": 1594197216000,
        "upd": 1594284393000,
        "rd_only": True,
        "crt_from": "WEB",
        "flg": {
        "status": -1,
        "duplicate": False
        },
        "w_flg": 0,
        "pub": False,
        "cntct": {
        "name": receiver1.name,
        "f_name": "porwal ambe medicals",
        "p_mob": "+91-9986238611"
        },
        "addr": {
        "city": "Dharwad",
        "state": "Karnataka",
        "a_l1": "opp old bus stand subhas road ",
        "plc_id": "18443f1f-9f5e-4e8c-8f99-9dc9bc43ea46",
        "loc": "\"dharwad r s\"",
        "pin": "580007",
        "s_dist": "dharwad",
        "dst": "dharwad",
        "cntry": "IN",
        "lmrk": ""
        },
        "geo": {
        "lat": 15.459898275,
        "long": 75.01109025,
        "accr": 26.126,
        "src": "CALC_AUTO"
        },
        "requires_docs_for_pickup": False
    },
    "receiver_contact": {
        "auser": True,
        "o_id": "0d31eb5f-5caf-491e-961c-bb399e655027",
        "o_ty": 2,
        "name": "Ambe Medical",
        "mob": "+91-8362221260"
    },
    "d_dpt": {
        "id": "1715630f-80e9-4732-8cc1-c3e92fbbf571",
        "dummy": False,
        "crt_from": "WEB",
        "def": False
    },
    "sec": [],
    "ept_w": {
        "start": 1443699853000,
        "end": 1443699853000,
        "anon": False
    },
    "e_eta": 1443714253000,
    "eta_ed": False,
    "c_per": 100,
    "s_updt": 1443761800000,
    "o_dt": 1443699918000,
    "lgl": {
        "toc_acpt": False,
        "invc_issd": False,
        "s_ack": "ackSHIP_IMG_cfdddccd-43b2-43ca-82bf-5ad8cf0dfeca_20151001_171703.jpg"
    },
    "p_mrt": "3f90cfa6-be56-420a-a96f-fb312f0fba37",
    "cust_shpr": False,
    "cust_rcvr": False,
    "u_shpr": False,
    "u_rcvr": False,
    "pck": False,
    "invc_tok": "9sIjQAjKbIhsPogEMe29nQ~~",
    "crt_s": "WEB",
    "trk_ids": [],
    "assoc": False,
    "nearby_delivery": False,
    "rcvr_walk": False,
    "shppr_walk": False
}
